### PR TITLE
Replace "date" and "date_str" fields/facets with "years"

### PR DESCRIPTION
**Pull request by sarastanton**
Remove `date` and `date_str` from list of conditional facet fields, and replace with `years`

### CODE REVIEW

**Review by blms — APPROVED** [review]
Looks great! I noticed one small thing, which is that Public Event and Writing both still display "No additional filters" even though the years facets are there.

I also want to make sure it's always actually going to be called `years` since it seems only Attendance and Writing seem to have any data in that field currently. Though, I imagine they probably just haven't prepared that data for most of the entity types yet.

Let's double-check that with Jay; if he confirms it's always `years`, and once you're able to solve the "no additional filters" issue, it's ready to merge!

**Comment by blms** [comment]
Re: limits from today's meeting, you can probably just keep increasing them for each facet that's missing entries until all the facet options show up (i.e. increasing more doesn't make any more appear). Let me know if anything goes wrong there! (I'm not sure if there's a hard limit to the number Elastic allows)

**Comment by sarastanton** [comment]
> Looks great! I noticed one small thing, which is that Public Event and Writing both still display "No additional filters" even though the years facets are there.

Ah, good catch! I added some more conditional logic to fix this.



> Re: limits from today's meeting, you can probably just keep increasing them for each facet that's missing entries until all the facet options show up (i.e. increasing more doesn't make any more appear). Let me know if anything goes wrong there! (I'm not sure if there's a hard limit to the number Elastic allows)

Done...although a few (`authors` and `performed_by`, for example) are ridiculously long (863 and 605 buckets, respectively) now. This might be something that gets revisited later on down the line.

**Review by blms — APPROVED** [review]
Looks great, ready to merge! 🚀 

> Done...although a few (`authors` and `performed_by`, for example) are ridiculously long (863 and 605 buckets, respectively) now. This might be something that gets revisited later on down the line.

Yes, especially since they seem to be slowing down the payload a bit. Might be a good argument for not using facets! Thanks for flagging.

**Pull request merged**
